INCLUDE_DIRS += Middlewares/SystemView/SystemView_Src/Config    \
                Middlewares/SystemView/SystemView_Src/SEGGER

DIRECTORIES += Middlewares/SystemView/SystemView_Src/Config     \
               Middlewares/SystemView/SystemView_Src/SEGGER

#C_SOURCES += Middlewares/SystemView/SystemView_Src/Config/SEGGER_SYSVIEW_Config_RTThread.c  \
#             Middlewares/SystemView/SystemView_Src/SEGGER/SEGGER_RTT.c
