DIRECTORIES += Application/src

C_SOURCES += Application/src/stm32f10x_it.c \
             Application/src/startup.c \
             Application/src/application.c	\
			 Application/src/network.c      \
             Application/src/wired_net.c    \
             Application/src/wireless_net.c 