DIRECTORIES += Middlewares/Eth

C_SOURCES += Middlewares/Eth/socket.c         \
             Middlewares/Eth/wizchip_conf.c   \
             Middlewares/Eth/dhcp.c           \
             Middlewares/Eth/dns.c            \
             Middlewares/Eth/network.c

