DIRECTORIES += Drivers/STM32F10x_StdPeriph_Driver/src

C_SOURCES += Drivers/STM32F10x_StdPeriph_Driver/src/misc.c          \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c  \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c  \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c  \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c  \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c  \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c   \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c \
			 Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c  