DIRECTORIES += Drivers/CMSIS/CM3/CoreSupport
DIRECTORIES += Drivers/CMSIS/CM3/DeviceSupport/ST/STM32F10x
DIRECTORIES += Drivers/CMSIS/CM3/DeviceSupport/ST/startup/gcc_ride7



C_SOURCES += Drivers/CMSIS/CM3/CoreSupport/core_cm3.c  \
             Drivers/CMSIS/CM3/DeviceSupport/ST/STM32F10x/system_stm32f10x.c  \
			 Drivers/CMSIS/CM3/DeviceSupport/ST/startup/gcc_ride7/startup_stm32f10x_hd.s

