INCLUDE_DIRS += Middlewares/RTOS/components/finsh    \
                Middlewares/RTOS/include			 \
                Middlewares/RTOS/libcpu/arm/common	 \
                Middlewares/RTOS/libcpu/arm/cortex-m3

DIRECTORIES += Middlewares/RTOS/components/finsh     \
               Middlewares/RTOS/libcpu/arm/common	 \
               Middlewares/RTOS/libcpu/arm/cortex-m3 \
               Middlewares/RTOS/src

C_SOURCES += Middlewares/RTOS/components/finsh/cmd.c				\
             Middlewares/RTOS/components/finsh/finsh_compiler.c     \
             Middlewares/RTOS/components/finsh/finsh_error.c    	\
             Middlewares/RTOS/components/finsh/finsh_heap.c         \
             Middlewares/RTOS/components/finsh/finsh_init.c         \
             Middlewares/RTOS/components/finsh/finsh_node.c         \
             Middlewares/RTOS/components/finsh/finsh_ops.c          \
             Middlewares/RTOS/components/finsh/finsh_parser.c       \
             Middlewares/RTOS/components/finsh/finsh_token.c        \
             Middlewares/RTOS/components/finsh/finsh_var.c          \
             Middlewares/RTOS/components/finsh/finsh_vm.c           \
             Middlewares/RTOS/components/finsh/msh_cmd.c            \
             Middlewares/RTOS/components/finsh/msh_file.c           \
             Middlewares/RTOS/components/finsh/msh.c                \
             Middlewares/RTOS/components/finsh/shell.c              \
             Middlewares/RTOS/components/finsh/symbol.c             \
             Middlewares/RTOS/libcpu/arm/common/backtrace.c         \
             Middlewares/RTOS/libcpu/arm/common/div0.c              \
             Middlewares/RTOS/libcpu/arm/common/showmem.c           \
             Middlewares/RTOS/libcpu/arm/cortex-m3/cpuport.c        \
             Middlewares/RTOS/src/clock.c                           \
             Middlewares/RTOS/src/components.c                      \
             Middlewares/RTOS/src/device.c                          \
             Middlewares/RTOS/src/idle.c                            \
             Middlewares/RTOS/src/ipc.c                             \
             Middlewares/RTOS/src/irq.c                             \
             Middlewares/RTOS/src/kservice.c                        \
             Middlewares/RTOS/src/mem.c                             \
             Middlewares/RTOS/src/memheap.c                         \
             Middlewares/RTOS/src/mempool.c                         \
             Middlewares/RTOS/src/module.c                          \
             Middlewares/RTOS/src/object.c                          \
             Middlewares/RTOS/src/scheduler.c                       \
             Middlewares/RTOS/src/signal.c                          \
             Middlewares/RTOS/src/slab.c                            \
             Middlewares/RTOS/src/thread.c                          \
             Middlewares/RTOS/src/timer.c


ASM_SOURCES += Middlewares/RTOS/libcpu/arm/cortex-m3/context_gcc.s
