INCLUDE_DIRS += Drivers/BSP/SX1276/src/radio	\
				Drivers/BSP/SX1276/src/config

DIRECTORIES += Drivers/BSP/SX1276/src/radio		\
			   Drivers/BSP/SX1276/src/config

C_SOURCES += Drivers/BSP/SX1276/src/radio/radio.c 			   \
			 Drivers/BSP/SX1276/src/radio/sx1276.c   		   \
			 Drivers/BSP/SX1276/src/radio/sx1276-LoRa.c		   \
			 Drivers/BSP/SX1276/src/radio/sx1276-LoRaMisc.c   \
			 Drivers/BSP/SX1276/src/config/sx1276-Hal.c