INCLUDE_DIRS += Middlewares/MQTT/MQTTPacket    \
                Middlewares/MQTT/MQTTClient-C

DIRECTORIES += Middlewares/MQTT/MQTTClient-C     \
               Middlewares/MQTT/MQTTPacket

C_SOURCES += Middlewares/MQTT/MQTTPacket/MQTTConnectClient.c            \
             Middlewares/MQTT/MQTTPacket/MQTTConnectServer.c            \
             Middlewares/MQTT/MQTTPacket/MQTTDeserializePublish.c       \
             Middlewares/MQTT/MQTTPacket/MQTTFormat.c                   \
             Middlewares/MQTT/MQTTPacket/MQTTPacket.c                   \
             Middlewares/MQTT/MQTTPacket/MQTTSerializePublish.c         \
             Middlewares/MQTT/MQTTPacket/MQTTSubscribeClient.c          \
             Middlewares/MQTT/MQTTPacket/MQTTSubscribeServer.c          \
             Middlewares/MQTT/MQTTPacket/MQTTUnsubscribeClient.c        \
             Middlewares/MQTT/MQTTPacket/MQTTUnsubscribeClient.c